services:
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
  
  barista:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./barista/Dockerfile
    ports:
      - "8003:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092


  beans:
    depends_on:
      kafka:
        condition: service_healthy
      barista:
        condition: service_started
    build:
      context: ./
      dockerfile: ./beans/Dockerfile
    ports:
      - "8002:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  orders:
    depends_on:
      kafka:
        condition: service_healthy
      beans:
        condition: service_started
    build:
      context: ./
      dockerfile: ./orders/Dockerfile
    ports:
      - "8001:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
